export const contractsSchema = {
  type: "object",
  properties: {
    id: { type: "string" },
    company: { type: "string" },
    businessId: { type: "string" },
    daysForBilling: { type: "string" },
    termsOfPayment: { type: "number" },
    deliveryFee: { type: "boolean" },
    factoring: { type: "boolean" },
    active: { type: "boolean" },
    stores: { type: "number" },
    createdOn: { type: "date" },
  },
};

export const contractsData = [
  {
    id: "1",
    company: "Tech Innovations Ltd.",
    businessId: "TI123456",
    daysForBilling: "30",
    termsOfPayment: 15,
    deliveryFee: true,
    factoring: false,
    active: true,
    stores: 5,
    createdOn: "2024-08-15T10:30:00Z",
  },
  {
    id: "2",
    company: "Green Energy Corp.",
    businessId: "GE654321",
    daysForBilling: "45",
    termsOfPayment: 30,
    deliveryFee: false,
    factoring: true,
    active: true,
    stores: 3,
    createdOn: "2024-07-22T14:45:00Z",
  },
  {
    id: "3",
    company: "Creative Solutions Inc.",
    businessId: "CS789012",
    daysForBilling: "15",
    termsOfPayment: 7,
    deliveryFee: true,
    factoring: false,
    active: false,
    stores: 7,
    createdOn: "2024-06-10T09:00:00Z",
  },
  {
    id: "4",
    company: "Alpha Systems LLC",
    businessId: "AS345678",
    daysForBilling: "60",
    termsOfPayment: 45,
    deliveryFee: false,
    factoring: true,
    active: true,
    stores: 10,
    createdOn: "2024-05-20T16:20:00Z",
  },
  {
    id: "5",
    company: "Bright Future Enterprises",
    businessId: "BF901234",
    daysForBilling: "30",
    termsOfPayment: 20,
    deliveryFee: true,
    factoring: true,
    active: false,
    stores: 2,
    createdOn: "2024-04-05T11:10:00Z",
  },
];
