import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import Providers from "../../providers/providers";
import "./../globals.css";
import AuthSession from "src/providers/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project 0",
  description: "Generated by create turbo",
};
export default function RootLayout({
  children,
}: {
  children: ReactNode;
}): JSX.Element {
  return (
    <html>
      <body className={inter.className}>
        <AuthSession>
          <Providers>{children}</Providers>
        </AuthSession>
      </body>
    </html>
  );
}
