import type { SchemaType } from "@repo/ayasofyazilim-ui/lib/create-zod-object";

export const $schema_details: SchemaType = {
  type: "object",
  displayName: "Example Schema Display Name", // Add this line
  properties: {
    taxFreeTagFacturaNumber: {
      type: "string",
      description: "The tax-free tag or invoice number.",
    },
    date: {
      type: "string",
      format: "date-time",
      description: "The date of the transaction.",
    },
    traveller: {
      type: "string",
      description: "The name of the traveller.",
    },
    company: {
      type: "string",
      description: "The name of the company involved in the transaction.",
    },
    salesAmount: {
      type: "number",
      description: "The amount of sales in the transaction.",
    },
    refund: {
      type: "number",
      description: "The amount refunded.",
    },
    status: {
      type: "string",
      enum: ["Pending", "Completed", "Cancelled"],
      description: "The status of the transaction.",
    },
  },
  required: [
    "taxFreeTagFacturaNumber",
    "date",
    "traveller",
    "company",
    "salesAmount",
    "refund",
    "status",
  ],
  additionalProperties: false,
};
export const $schema_list = [
  {
    taxFreeTagFacturaNumber: "TF123456",
    date: "2024-08-01",
    traveller: "Alice Johnson",
    company: "TravelTech Ltd.",
    salesAmount: 1200.0,
    refund: 100.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123457",
    date: "2024-08-02",
    traveller: "Bob Smith",
    company: "Global Tours Inc.",
    salesAmount: 800.0,
    refund: 50.0,
    status: "Pending",
  },
  {
    taxFreeTagFacturaNumber: "TF123458",
    date: "2024-08-03",
    traveller: "Carol Davis",
    company: "Holiday Makers",
    salesAmount: 1500.0,
    refund: 200.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123459",
    date: "2024-08-04",
    traveller: "David Wilson",
    company: "TravelTech Ltd.",
    salesAmount: 500.0,
    refund: 0.0,
    status: "Cancelled",
  },
  {
    taxFreeTagFacturaNumber: "TF123460",
    date: "2024-08-05",
    traveller: "Emma Brown",
    company: "Global Tours Inc.",
    salesAmount: 1000.0,
    refund: 75.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123461",
    date: "2024-08-06",
    traveller: "Frank Harris",
    company: "Holiday Makers",
    salesAmount: 600.0,
    refund: 60.0,
    status: "Pending",
  },
  {
    taxFreeTagFacturaNumber: "TF123462",
    date: "2024-08-07",
    traveller: "Grace Lee",
    company: "TravelTech Ltd.",
    salesAmount: 900.0,
    refund: 90.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123463",
    date: "2024-08-08",
    traveller: "Henry Clark",
    company: "Global Tours Inc.",
    salesAmount: 750.0,
    refund: 30.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123464",
    date: "2024-08-09",
    traveller: "Ivy Martinez",
    company: "Holiday Makers",
    salesAmount: 1300.0,
    refund: 150.0,
    status: "Pending",
  },
  {
    taxFreeTagFacturaNumber: "TF123465",
    date: "2024-08-10",
    traveller: "Jack Thompson",
    company: "TravelTech Ltd.",
    salesAmount: 400.0,
    refund: 20.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123466",
    date: "2024-08-11",
    traveller: "Karen White",
    company: "Global Tours Inc.",
    salesAmount: 1100.0,
    refund: 120.0,
    status: "Cancelled",
  },
  {
    taxFreeTagFacturaNumber: "TF123467",
    date: "2024-08-12",
    traveller: "Louis Anderson",
    company: "Holiday Makers",
    salesAmount: 1400.0,
    refund: 200.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123468",
    date: "2024-08-13",
    traveller: "Mona Harris",
    company: "TravelTech Ltd.",
    salesAmount: 850.0,
    refund: 90.0,
    status: "Pending",
  },
  {
    taxFreeTagFacturaNumber: "TF123469",
    date: "2024-08-14",
    traveller: "Nathan King",
    company: "Global Tours Inc.",
    salesAmount: 550.0,
    refund: 30.0,
    status: "Completed",
  },
  {
    taxFreeTagFacturaNumber: "TF123470",
    date: "2024-08-15",
    traveller: "Olivia Scott",
    company: "Holiday Makers",
    salesAmount: 1600.0,
    refund: 180.0,
    status: "Cancelled",
  },
];
