import type { NavigationItem } from "@repo/ui/main-layout";
import {
  Presentation,
  AlertCircle,
  Settings,
  BarChart,
  Layers,
  FileText,
  ClipboardList,
  Book,
  File,
  Database,
  Network,
  Globe,
} from "lucide-react";

export type NavigationItmes = NavigationItem & {
  type: string | string[];
  appType?: string;
};

export const navigationItemsTemp: NavigationItmes[] = [
  {
    key: "devices",
    title: "Devices",
    href: "/devices",
    type: "admin",
    appType: "unirefund",
    icon: <Presentation className="w-4 text-slate-500" />,
  },
  {
    key: "registered_errors",
    title: "Registered Errors",
    href: "/registered-errors",
    type: "admin",
    appType: "unirefund",
    icon: <AlertCircle className="w-4 text-slate-500" />,
  },
  {
    key: "config",
    title: "Config",
    href: "/config",
    type: "admin",
    appType: "unirefund",
    icon: <Settings className="w-4 text-slate-500" />,
  },
  {
    key: "groups",
    title: "Groups",
    href: "/groups",
    type: "admin",
    appType: "unirefund",
    icon: <Layers className="w-4 text-slate-500" />,
  },
  {
    key: "finance",
    title: "Finance",
    href: "/finance",
    type: "admin",
    appType: "unirefund",
    icon: <BarChart className="w-4 text-slate-500" />,
    submenu: [
      {
        key: "reports",
        title: "Reports",
        href: "/finance/reports",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "invoices",
        title: "Invoices",
        href: "/finance/invoices",
        icon: <File className="w-4 text-slate-500" />,
      },
      {
        key: "import_payments",
        title: "Import Payments",
        href: "/finance/import-payments",
        icon: <ClipboardList className="w-4 text-slate-500" />,
      },
      {
        key: "rebates",
        title: "Rebates",
        href: "/finance/rebates",
        icon: <Book className="w-4 text-slate-500" />,
      },
      {
        key: "bookkeeping",
        title: "Bookkeeping",
        href: "/finance/bookkeeping",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "age",
        title: "Age",
        href: "/finance/age",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "balance",
        title: "Balance",
        href: "/finance/balance",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "invoicing_management",
        title: "Invoicing Management",
        href: "/finance/invoicing-management",
        icon: <FileText className="w-4 text-slate-500" />,
      },
    ],
  },
  {
    key: "settings",
    title: "Settings",
    href: "/settings",
    type: "admin",
    appType: "unirefund",
    icon: <Settings className="w-4 text-slate-500" />,
  },
  {
    key: "logs",
    title: "Logs",
    href: "/logs",
    type: "admin",
    appType: "unirefund",
    icon: <FileText className="w-4 text-slate-500" />,
  },
  {
    key: "api_logs",
    title: "API Logs",
    href: "/api-logs",
    type: "admin",
    appType: "unirefund",
    icon: <Database className="w-4 text-slate-500" />,
  },
  {
    key: "systems",
    title: "Systems",
    href: "/systems",
    type: "admin",
    appType: "unirefund",
    icon: <Network className="w-4 text-slate-500" />,
  },
  {
    key: "planet_web",
    title: "Planet Web",
    href: "/planet-web",
    type: "admin",
    appType: "unirefund",
    icon: <Globe className="w-4 text-slate-500" />,
    submenu: [
      {
        key: "issue",
        title: "Issue",
        href: "/planet-web/issue",
        icon: <AlertCircle className="w-4 text-slate-500" />,
      },
      {
        key: "tax_free_tags",
        title: "Tax Free Tags",
        href: "/planet-web/tax-free-tags",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "refund",
        title: "Refund",
        href: "/planet-web/refund",
        icon: <FileText className="w-4 text-slate-500" />,
        submenu: [
          {
            key: "refunds",
            title: "Refunds",
            href: "/planet-web/refund/refunds",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "travellers",
            title: "Travellers",
            href: "/planet-web/refund/travellers",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "sticker_status",
            title: "Sticker Status",
            href: "/planet-web/refund/sticker-status",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "reconciliation",
            title: "Reconciliation",
            href: "/planet-web/refund/reconciliation",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "card_payments",
            title: "Card Payments",
            href: "/planet-web/refund/card-payments",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "payment_requests",
            title: "Payment Requests",
            href: "/planet-web/refund/payment-requests",
            icon: <FileText className="w-4 text-slate-500" />,
          },
        ],
      },
      {
        key: "settings",
        title: "Settings",
        href: "/planet-web/settings",
        icon: <Settings className="w-4 text-slate-500" />,
      },
      {
        key: "reports",
        title: "Reports",
        href: "/planet-web/reports",
        icon: <FileText className="w-4 text-slate-500" />,
        submenu: [
          {
            key: "daily_report",
            title: "Daily Report",
            href: "/planet-web/reports/daily-report",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "dashboard",
            title: "Dashboard",
            href: "/planet-web/reports/dashboard",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "issued",
            title: "Issued",
            href: "/planet-web/reports/issued",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "by_store",
            title: "By Store",
            href: "/planet-web/reports/by-store",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "validation",
            title: "Validation",
            href: "/planet-web/reports/validation",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "invoice",
            title: "Invoice",
            href: "/planet-web/reports/invoice",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "travellers",
            title: "Travellers",
            href: "/planet-web/reports/travellers",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "validation_rules_hits",
            title: "Validation Rules Hits",
            href: "/planet-web/reports/validation-rules-hits",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "others",
            title: "Others",
            href: "/planet-web/reports/others",
            icon: <FileText className="w-4 text-slate-500" />,
          },
          {
            key: "change_report",
            title: "Change Report",
            href: "/planet-web/reports/change-report",
            icon: <FileText className="w-4 text-slate-500" />,
          },
        ],
      },
    ],
  },
];
