import type { NavigationItem } from "@repo/ui/main-layout";
import {
  Presentation,
  AlertCircle,
  Settings,
  BarChart,
  Layers,
  FileText,
  ClipboardList,
  Book,
  File,
  Database,
  Network,
  Globe,
} from "lucide-react";
import { getBaseLink } from "src/utils";

export type NavigationItmes = NavigationItem & {
  type: string | string[];
  appType?: string;
};

export const navigationItemsTemp: NavigationItmes[] = [
  {
    key: "operations",
    title: "Operations",
    href: "/operations",
    type: "admin",
    appType: "unirefund",
    icon: <Globe className="w-4 text-slate-500" />,
    submenu: [
      {
        key: "tax_free_tags",
        title: "Tax Free Tags",
        href: getBaseLink("app/admin/operations/details", true),
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "issue",
        wip: true,
        title: "Issue",
        href: "/operation/issue",
        icon: <AlertCircle className="w-4 text-slate-500" />,
      },
      {
        key: "settings",
        wip: true,
        title: "Settings",
        href: "/operation/settings",
        icon: <Settings className="w-4 text-slate-500" />,
      },
    ],
  },
  {
    key: "devices",
    wip: true,
    title: "Devices",
    href: "/devices",
    type: "admin",
    appType: "unirefund",
    icon: <Presentation className="w-4 text-slate-500" />,
  },
  {
    key: "registered_errors",
    wip: true,
    title: "Registered Errors",
    href: "/registered-errors",
    type: "admin",
    appType: "unirefund",
    icon: <AlertCircle className="w-4 text-slate-500" />,
  },
  {
    key: "config",
    wip: true,
    title: "Config",
    href: "/config",
    type: "admin",
    appType: "unirefund",
    icon: <Settings className="w-4 text-slate-500" />,
  },
  {
    key: "groups",
    wip: true,
    title: "Groups",
    href: "/groups",
    type: "admin",
    appType: "unirefund",
    icon: <Layers className="w-4 text-slate-500" />,
  },
  {
    key: "finance",
    wip: true,
    title: "Finance",
    href: "/finance",
    type: "admin",
    appType: "unirefund",
    icon: <BarChart className="w-4 text-slate-500" />,
    submenu: [
      {
        key: "reports",
        wip: true,
        title: "Reports",
        href: "/finance/reports",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "invoices",
        wip: true,
        title: "Invoices",
        href: "/finance/invoices",
        icon: <File className="w-4 text-slate-500" />,
      },
      {
        key: "import_payments",
        wip: true,
        title: "Import Payments",
        href: "/finance/import-payments",
        icon: <ClipboardList className="w-4 text-slate-500" />,
      },
      {
        key: "rebates",
        wip: true,
        title: "Rebates",
        href: "/finance/rebates",
        icon: <Book className="w-4 text-slate-500" />,
      },
      {
        key: "bookkeeping",
        wip: true,
        title: "Bookkeeping",
        href: "/finance/bookkeeping",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "age",
        wip: true,
        title: "Age",
        href: "/finance/age",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "balance",
        wip: true,
        title: "Balance",
        href: "/finance/balance",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "invoicing_management",
        wip: true,
        title: "Invoicing Management",
        href: "/finance/invoicing-management",
        icon: <FileText className="w-4 text-slate-500" />,
      },
    ],
  },
  {
    key: "settings",
    wip: true,
    title: "Settings",
    href: "/settings",
    type: "admin",
    appType: "unirefund",
    icon: <Settings className="w-4 text-slate-500" />,
  },
  {
    key: "logs",
    wip: true,
    title: "Logs",
    href: "/logs",
    type: "admin",
    appType: "unirefund",
    icon: <FileText className="w-4 text-slate-500" />,
  },
  {
    key: "api_logs",
    wip: true,
    title: "API Logs",
    href: "/api-logs",
    type: "admin",
    appType: "unirefund",
    icon: <Database className="w-4 text-slate-500" />,
  },
  {
    key: "systems",
    wip: true,
    title: "Systems",
    href: "/systems",
    type: "admin",
    appType: "unirefund",
    icon: <Network className="w-4 text-slate-500" />,
  },
  {
    key: "reports",
    wip: true,
    title: "Reports",
    href: "/operation/reports",
    icon: <FileText className="w-4 text-slate-500" />,
    type: "admin",
    appType: "unirefund",
    submenu: [
      {
        key: "daily_report",
        wip: true,
        title: "Daily Report",
        href: "/operation/reports/daily-report",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "dashboard",
        wip: true,
        title: "Dashboard",
        href: "/operation/reports/dashboard",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "issued",
        wip: true,
        title: "Issued",
        href: "/operation/reports/issued",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "by_store",
        wip: true,
        title: "By Store",
        href: "/operation/reports/by-store",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "validation",
        wip: true,
        title: "Validation",
        href: "/operation/reports/validation",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "invoice",
        wip: true,
        title: "Invoice",
        href: "/operation/reports/invoice",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "travellers",
        wip: true,
        title: "Travellers",
        href: "/operation/reports/travellers",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "validation_rules_hits",
        wip: true,
        title: "Validation Rules Hits",
        href: "/operation/reports/validation-rules-hits",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "others",
        wip: true,
        title: "Others",
        href: "/operation/reports/others",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "change_report",
        wip: true,
        title: "Change Report",
        href: "/operation/reports/change-report",
        icon: <FileText className="w-4 text-slate-500" />,
      },
    ],
  },
  {
    key: "refund",
    wip: true,
    title: "Refund",
    href: "/operation/refund",
    icon: <FileText className="w-4 text-slate-500" />,
    type: "admin",
    appType: "unirefund",
    submenu: [
      {
        key: "refunds",
        wip: true,
        title: "Refunds",
        href: "/operation/refund/refunds",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "travellers",
        wip: true,
        title: "Travellers",
        href: "/operation/refund/travellers",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "sticker_status",
        wip: true,
        title: "Sticker Status",
        href: "/operation/refund/sticker-status",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "reconciliation",
        wip: true,
        title: "Reconciliation",
        href: "/operation/refund/reconciliation",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "card_payments",
        wip: true,
        title: "Card Payments",
        href: "/operation/refund/card-payments",
        icon: <FileText className="w-4 text-slate-500" />,
      },
      {
        key: "payment_requests",
        wip: true,
        title: "Payment Requests",
        href: "/operation/refund/payment-requests",
        icon: <FileText className="w-4 text-slate-500" />,
      },
    ],
  },
];
